export type Locale = "vi" | "en";


const vi = {
  navToday: "Hôm nay", navHabits: "Thói quen", navInsights: "Phân tích", navTree: "Cây tiến bộ", navSettings: "Cài đặt",
  appTagline: "Từng bước nhỏ, một nhịp sống bền vững", menu: "Điều hướng", close: "Đóng", logout: "Đăng xuất", themeLight: "Giao diện sáng", themeDark: "Giao diện tối", language: "Ngôn ngữ", openAssistant: "Mở trợ lý",
  dashboardEyebrow: "Nhịp sống hôm nay", dashboardTitle: "Hôm nay của bạn", dashboardEmptyDescription: "Hãy lên lịch thói quen đầu tiên cho hôm nay.", dashboardWaiting: "{count} thói quen đang chờ bạn hoàn thành.", addHabit: "Thêm thói quen", todayProgress: "Tiến độ hôm nay", completed: "đã hoàn thành", growthCompanion: "Người bạn đồng hành", progressTree: "Cây tiến bộ", level: "Cấp", todayList: "Danh sách hôm nay", nextSteps: "Những bước cần đi", todayEmpty: "Hôm nay đang trống", todayEmptyDescription: "Lịch của bạn chưa có thói quen nào cho ngày này.", openHabitSchedule: "Mở lịch thói quen",
  habitsEyebrow: "Nhịp tuần của riêng bạn", habitsTitle: "Thói quen", habitsDescription: "Thiết kế một nhịp tuần vừa sức, rồi để những bước nhỏ tích lũy thành thay đổi lớn.", everyDay: "Mỗi ngày", currentStreak: "Chuỗi hiện tại", totalCompletions: "Lần hoàn thành", doneToday: "Đã hoàn thành hôm nay", markComplete: "Đánh dấu hoàn thành", scheduleEmpty: "Lịch đang trống", scheduleEmptyDescription: "Tạo thói quen đầu tiên và chọn ngày trực tiếp trên lịch tuyến tính.", completedToday: "Đã hoàn thành hôm nay", keptRhythm: "Bạn đã giữ nhịp cho “{name}”.", streakBonus: "gồm {bonus} EXP thưởng chuỗi",
  insightsEyebrow: "Nhìn lại để bước tiếp", insightsTitle: "Phân tích tiến độ", insightsDescription: "Đọc nhịp 30 ngày gần nhất và nhận ra những khoảng thời gian bạn bền bỉ nhất.", exportData: "Xuất dữ liệu", tasksCompleted: "Đã hoàn thành", bestStreak: "Chuỗi tốt nhất", mostConsistent: "Ổn định nhất", times: "lần", days: "ngày", noData: "chưa có dữ liệu", rhythm12Weeks: "Nhịp độ 12 tuần", eachCellDay: "Mỗi ô là một ngày", less: "Ít", more: "Nhiều", activityMap: "Bản đồ hoạt động",
  treeEyebrow: "Thành quả hữu hình", treeTitle: "Cây tiến bộ", treeDescription: "Mỗi lần hoàn thành thói quen sẽ nuôi cây lớn lên cùng bạn.", currentLevel: "Cấp độ hiện tại", branch: "Nhánh", branchTech: "Công nghệ", branchScholar: "Tri thức", branchNature: "Tự nhiên", expToNext: "{count} EXP nữa để đạt cấp tiếp theo", inventory: "Kho đồ", items: "Vật phẩm", achievements: "Cột mốc", milestones: "Thành tựu", inventoryEmpty: "Vật phẩm sẽ xuất hiện khi cây lên cấp.", achievementEmpty: "Duy trì chuỗi ngày để mở khóa thành tựu.", fertilizer: "Phân bón", magicWater: "Nước phép", decorativePot: "Chậu trang trí", firstSeven: "Chuỗi 7 ngày đầu tiên", treeReached: "Cây đạt cấp {level}",
  settingsEyebrow: "Không gian cá nhân", settingsTitle: "Hồ sơ của bạn", settingsDescription: "Quản lý danh tính, tùy chọn trải nghiệm và bảo mật tài khoản.", joined: "Tham gia", loginStreak: "Chuỗi đăng nhập", loginDays: "{count} ngày đăng nhập", profileInfo: "Thông tin cơ bản", displayName: "Tên thường gọi", email: "Email", newPassword: "Mật khẩu mới", passwordHint: "Để trống nếu không đổi", saveChanges: "Lưu thay đổi", deleteAccount: "Xóa tài khoản", deleteDescription: "Toàn bộ thói quen, lịch sử, cây tiến bộ và tin nhắn sẽ bị xóa vĩnh viễn.", confirmDelete: "Xác nhận xóa tài khoản", confirmDeleteDescription: "Nhập lại chính xác email {email}. Thao tác này không thể hoàn tác.", confirmEmail: "Email xác nhận", cancel: "Hủy", deleting: "Đang xóa...", deleteForever: "Xóa vĩnh viễn", profileUpdated: "Đã cập nhật hồ sơ", profileUpdatedDescription: "Thông tin tài khoản của bạn đã được lưu thành công.",
  assistantName: "Trợ lý HabiStride", ready: "Sẵn sàng", fallback: "Dự phòng", focusMode: "Chế độ tập trung", exitFocus: "Thu nhỏ", assistantEmpty: "Bạn cần hỗ trợ gì?", assistantEmptyDescription: "Hỏi về thói quen hoặc tiến độ gần đây.", you: "Bạn", replying: "đang trả lời", thinking: "Đang suy nghĩ...", messagePlaceholder: "Nhập tin nhắn...", send: "Gửi", justNow: "Vừa xong", sentMinutes: "Đã gửi {count} phút trước",
  authEyebrow: "Tiến từng bước, đều mỗi ngày", authHero: "Thói quen nhỏ. Thay đổi bền lâu.", authStory: "Ghi lại điều quan trọng, giữ nhịp mỗi ngày và nhìn hành trình của bạn nở thành một tán cây sống động.", authQuote: "Hôm nay chỉ cần tốt hơn hôm qua một chút.", welcomeBack: "Chào mừng trở lại", startJourney: "Tạo hành trình mới", login: "Đăng nhập", register: "Tạo tài khoản", loginDescription: "Đăng nhập để tiếp tục nhịp sống hôm nay.", registerDescription: "Xác minh email để bắt đầu hành trình của riêng bạn.", password: "Mật khẩu", passwordPlaceholder: "Tối thiểu 8 ký tự", processing: "Đang xử lý...", sendVerification: "Gửi mã xác minh", or: "hoặc", noAccount: "Chưa có tài khoản?", hasAccount: "Đã có tài khoản?", signUp: "Đăng ký", verifyEmail: "Xác minh email", enterOtp: "Nhập mã OTP", otpSent: "Mã 6 chữ số đã được gửi đến {email}.", verificationCode: "Mã xác minh", verifying: "Đang xác minh...", verifyAndRegister: "Xác minh và đăng ký", changeEmail: "Đổi email", resendAfter: "Gửi lại sau {count}s", resendCode: "Gửi lại mã", emailInvalid: "Email không đúng định dạng.", passwordLength: "Mật khẩu phải có ít nhất 8 ký tự.", passwordStrength: "Mật khẩu phải có ít nhất một chữ cái và một chữ số.", otpInvalid: "Mã OTP phải gồm đúng 6 chữ số.", googleError: "Không thể đăng nhập với Google.",
  quickSetup: "Thiết lập nhanh", callYouRight: "Để HabiStride gọi bạn đúng tên", onboardingDescription: "Hoàn thiện hai thông tin cơ bản. Bạn vẫn có thể thay đổi sau.", chooseAvatar: "Chọn ảnh đại diện", avatarTypes: "JPEG, PNG hoặc WebP · tối đa 2 MB", selectedAvatar: "Ảnh đại diện đã chọn", namePlaceholder: "Tên bạn muốn được gọi", later: "Để sau", saving: "Đang lưu...", finishProfile: "Hoàn tất hồ sơ", chooseAvatarError: "Vui lòng chọn ảnh đại diện.", habitSchedule: "Lịch thực hiện", smallStepRightDay: "Một bước nhỏ, đúng ngày", habitDialogDescription: "Chọn những ngày bạn muốn thói quen xuất hiện trong danh sách hôm nay.", habitName: "Tên thói quen", habitExample: "Ví dụ: Đọc sách 20 phút", category: "Danh mục", knowledge: "Kiến thức", health: "Sức khỏe", code: "Lập trình", other: "Khác", activeDays: "Ngày thực hiện", choose: "Chọn", daysPerWeek: "{count} ngày mỗi tuần", seeding: "Đang gieo mầm...", saveHabit: "Lưu thói quen", selectDayError: "Hãy chọn ít nhất một ngày.", habitCreated: "Thói quen đã được tạo", habitCreatedDescription: "“{name}” đã có trong lịch của bạn. Bắt đầu nhỏ và giữ nhịp đều.", continue: "Tiếp tục", loginRewardTitle: "Chuỗi đăng nhập {count} ngày", loginRewardDescription: "Bạn đã giữ nhịp đăng nhập đều đặn và mở khóa một phần thưởng mới.", received: "Đã nhận: {item}", loading: "Đang chuẩn bị hành trình",
  monday: "Thứ hai", tuesday: "Thứ ba", wednesday: "Thứ tư", thursday: "Thứ năm", friday: "Thứ sáu", saturday: "Thứ bảy", sunday: "Chủ nhật",
} as const;

export type MessageKey = keyof typeof vi;
export const messages: Record<Locale, Record<MessageKey, string>> = { vi, en: {
  ...vi,
  navToday: "Today", navHabits: "Habits", navInsights: "Insights", navTree: "Growth tree", navSettings: "Settings", appTagline: "Small steps, a sustainable rhythm", menu: "Navigation", close: "Close", logout: "Log out", themeLight: "Light appearance", themeDark: "Dark appearance", language: "Language", openAssistant: "Open assistant",
  dashboardEyebrow: "Today's rhythm", dashboardTitle: "Your day, in motion", dashboardEmptyDescription: "Schedule your first habit for today.", dashboardWaiting: "{count} habits are waiting for you.", addHabit: "Add habit", todayProgress: "Today's progress", completed: "completed", growthCompanion: "Growth companion", progressTree: "Progress tree", level: "Level", todayList: "Today's list", nextSteps: "The next small steps", todayEmpty: "A clear day", todayEmptyDescription: "There are no habits scheduled for today yet.", openHabitSchedule: "Open habit schedule",
  habitsEyebrow: "A rhythm that fits you", habitsTitle: "Habits", habitsDescription: "Shape a realistic week, then let small repeated steps compound into meaningful change.", everyDay: "Every day", currentStreak: "Current streak", totalCompletions: "Completions", doneToday: "Completed today", markComplete: "Mark complete", scheduleEmpty: "Your schedule is open", scheduleEmptyDescription: "Create your first habit and choose its days on the weekly timeline.", completedToday: "Completed for today", keptRhythm: "You kept the rhythm for “{name}”.", streakBonus: "including {bonus} streak bonus EXP",
  insightsEyebrow: "Look back, move forward", insightsTitle: "Progress insights", insightsDescription: "Read your latest 30-day rhythm and discover where consistency is taking root.", exportData: "Export data", tasksCompleted: "Completed", bestStreak: "Best streak", mostConsistent: "Most consistent", times: "times", days: "days", noData: "no data yet", rhythm12Weeks: "12-week rhythm", eachCellDay: "Every cell is one day", less: "Less", more: "More", activityMap: "Activity map",
  treeEyebrow: "Progress you can see", treeTitle: "Growth tree", treeDescription: "Every completed habit helps your tree grow alongside you.", currentLevel: "Current level", branch: "Path", branchTech: "Technology", branchScholar: "Knowledge", branchNature: "Nature", expToNext: "{count} EXP until the next level", inventory: "Inventory", items: "Items", achievements: "Milestones", milestones: "Achievements", inventoryEmpty: "New items appear as your tree levels up.", achievementEmpty: "Keep a streak going to unlock achievements.", fertilizer: "Fertilizer", magicWater: "Magic water", decorativePot: "Decorative pot", firstSeven: "First 7-day streak", treeReached: "Tree reached level {level}",
  settingsEyebrow: "Your own space", settingsTitle: "Your profile", settingsDescription: "Manage your identity, experience preferences, and account security.", joined: "Joined", loginStreak: "Login streak", loginDays: "{count} login days", profileInfo: "Profile details", displayName: "Display name", newPassword: "New password", passwordHint: "Leave blank to keep it", saveChanges: "Save changes", deleteAccount: "Delete account", deleteDescription: "All habits, history, tree progress, and messages will be permanently deleted.", confirmDelete: "Confirm account deletion", confirmDeleteDescription: "Enter {email} exactly. This action cannot be undone.", confirmEmail: "Confirmation email", cancel: "Cancel", deleting: "Deleting...", deleteForever: "Delete permanently", profileUpdated: "Profile updated", profileUpdatedDescription: "Your account information was saved successfully.",
  assistantName: "HabiStride assistant", ready: "Ready", fallback: "Fallback", focusMode: "Focus mode", exitFocus: "Minimize", assistantEmpty: "How can I support you?", assistantEmptyDescription: "Ask about your habits or recent progress.", you: "You", replying: "replying", thinking: "Thinking...", messagePlaceholder: "Write a message...", send: "Send", justNow: "Just now", sentMinutes: "Sent {count} minutes ago",
  authEyebrow: "Small steps, every day", authHero: "Small habits. Lasting change.", authStory: "Capture what matters, keep your daily rhythm, and watch your journey grow into something alive.", authQuote: "Today only needs to be a little better than yesterday.", welcomeBack: "Welcome back", startJourney: "Begin a new journey", login: "Log in", register: "Create account", loginDescription: "Sign in to continue today's rhythm.", registerDescription: "Verify your email to begin a journey of your own.", password: "Password", passwordPlaceholder: "At least 8 characters", processing: "Processing...", sendVerification: "Send verification code", or: "or", noAccount: "New to HabiStride?", hasAccount: "Already have an account?", signUp: "Sign up", verifyEmail: "Verify email", enterOtp: "Enter your OTP", otpSent: "A six-digit code was sent to {email}.", verificationCode: "Verification code", verifying: "Verifying...", verifyAndRegister: "Verify and create account", changeEmail: "Change email", resendAfter: "Resend in {count}s", resendCode: "Resend code", emailInvalid: "Enter a valid email address.", passwordLength: "Password must have at least 8 characters.", passwordStrength: "Password needs at least one letter and one number.", otpInvalid: "The OTP must contain exactly six digits.", googleError: "Could not sign in with Google.",
  quickSetup: "Quick setup", callYouRight: "Help HabiStride know your name", onboardingDescription: "Complete two simple details. You can change them later.", chooseAvatar: "Choose a profile photo", avatarTypes: "JPEG, PNG or WebP · up to 2 MB", selectedAvatar: "Selected profile photo", namePlaceholder: "What should we call you?", later: "Later", saving: "Saving...", finishProfile: "Finish profile", chooseAvatarError: "Please choose a profile photo.", habitSchedule: "Habit schedule", smallStepRightDay: "A small step, on the right day", habitDialogDescription: "Choose the days this habit should appear on today's list.", habitName: "Habit name", habitExample: "Example: Read for 20 minutes", category: "Category", knowledge: "Knowledge", health: "Health", code: "Coding", other: "Other", activeDays: "Active days", choose: "Select", daysPerWeek: "{count} days per week", seeding: "Planting...", saveHabit: "Save habit", selectDayError: "Choose at least one day.", habitCreated: "Habit created", habitCreatedDescription: "“{name}” is now in your schedule. Start small and keep the rhythm.", continue: "Continue", loginRewardTitle: "{count}-day login streak", loginRewardDescription: "You kept a steady login rhythm and unlocked a new reward.", received: "Received: {item}", loading: "Preparing your journey", monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", saturday: "Saturday", sunday: "Sunday",
} };

export function interpolate(value: string, values?: Record<string, string | number>) {
  return values ? Object.entries(values).reduce((result, [key, replacement]) => result.replaceAll(`{${key}}`, String(replacement)), value) : value;
}
