"use client";
/* eslint-disable @next/next/no-img-element */
import { CalendarDays, Camera, Flame, LogOut, ShieldCheck, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";
import { V2PageHeader } from "@/components/v2/page-header";
import { V2SuccessDialog } from "@/components/v2/success-dialog";
import { V2LoadingState as LoadingState } from "@/components/v2/loading-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiClient } from "@/lib/api-client";
import { session } from "@/lib/session";
import { getErrorMessage } from "@/lib/utils";
import type { UpdateUserRequest, User } from "@/types/contracts";
import { usePreferences } from "@/components/providers/preferences-provider";

export default function SettingsV2Page(){const router=useRouter();const{locale,t}=usePreferences();const fileRef=useRef<HTMLInputElement>(null);const[user,setUser]=useState<User|null>(null);const[error,setError]=useState("");const[success,setSuccess]=useState(false);const[deleteOpen,setDeleteOpen]=useState(false);const[deleting,setDeleting]=useState(false);useEffect(()=>{const current=session.user();if(!current)return;apiClient<User>(`/users/${current.id}`).then(value=>{session.updateUser(value);setUser(value);}).catch(reason=>setError(getErrorMessage(reason)));},[]);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!user)return;setError("");const form=new FormData(event.currentTarget);const payload:UpdateUserRequest={email:String(form.get("email")),displayName:String(form.get("displayName"))};const password=String(form.get("password")||"");if(password)payload.password=password;try{updateUser(await apiClient<User>(`/users/${user.id}`,{method:"PATCH",body:JSON.stringify(payload)}));setSuccess(true);}catch(reason){setError(getErrorMessage(reason));}}async function upload(file?:File){if(!file||!user)return;setError("");const body=new FormData();body.append("avatar",file);try{updateUser(await apiClient<User>(`/users/${user.id}/avatar`,{method:"POST",body}));setSuccess(true);}catch(reason){setError(getErrorMessage(reason));}}async function remove(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!user)return;const email=String(new FormData(event.currentTarget).get("confirmEmail")||"").trim();setDeleting(true);setError("");try{await apiClient(`/users/${user.id}`,{method:"DELETE",body:JSON.stringify({email})});session.clear();router.replace("/register");}catch(reason){setError(getErrorMessage(reason));setDeleting(false);}}function updateUser(value:User){session.updateUser(value);setUser(value);}function logout(){session.clear();router.replace("/login");}if(!user)return <LoadingState/>;const joined=new Intl.DateTimeFormat(locale==="vi"?"vi-VN":"en-US",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(user.createdAt));const avatar=user.avatarUrl?<img src={user.avatarUrl} alt=""/>:<span>{(user.displayName||user.email)[0].toUpperCase()}</span>;
  return <div className="v2-view"><V2PageHeader eyebrow={t("settingsEyebrow")} title={t("settingsTitle")} description={t("settingsDescription")}/><section className="v2-profile-hero" data-reveal><button className="v2-profile-avatar" type="button" onClick={()=>fileRef.current?.click()}>{avatar}<i><Camera/></i></button><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>upload(event.target.files?.[0])}/><div className="v2-profile-copy"><h2>{user.displayName||user.email.split("@")[0]}</h2><p>{user.email}</p><Badge>{user.authProvider==="google"?"Google":"Email"}</Badge></div><div className="v2-profile-stat"><CalendarDays/><span>{t("joined")}</span><strong>{joined}</strong></div><div className="v2-profile-stat"><Flame/><span>{t("loginStreak")}</span><strong>{user.stat?.currentLoginStreak||0} {t("days")}</strong><small>{t("loginDays",{count:user.stat?.totalLoginDays||0})}</small></div></section><section className="v2-settings-grid"><form onSubmit={save} className="v2-settings-form" data-stack-card><div className="v2-settings-heading"><div><p>{t("profileInfo")}</p><h2>{t("settingsTitle")}</h2></div><ShieldCheck/></div><Label>{t("displayName")}<Input name="displayName" defaultValue={user.displayName||""} required maxLength={60}/></Label><Label>{t("email")}<Input name="email" type="email" defaultValue={user.email} required/></Label><Label>{t("newPassword")}<Input name="password" type="password" placeholder={t("passwordHint")} minLength={8}/></Label>{error&&<div className="error-box">{error}</div>}<div className="v2-settings-actions"><Button>{t("saveChanges")}</Button><Button type="button" variant="outline" onClick={logout}><LogOut/>{t("logout")}</Button></div></form><aside className="v2-danger" data-stack-card><Trash2/><div><h2>{t("deleteAccount")}</h2><p>{t("deleteDescription")}</p></div><Button variant="outline" onClick={()=>setDeleteOpen(true)}><Trash2/>{t("deleteAccount")}</Button></aside></section><Dialog open={deleteOpen} onOpenChange={setDeleteOpen}><DialogContent className="v2-delete-dialog"><DialogHeader><DialogTitle>{t("confirmDelete")}</DialogTitle><DialogDescription>{t("confirmDeleteDescription",{email:user.email})}</DialogDescription></DialogHeader><form onSubmit={remove}><Label>{t("confirmEmail")}<Input name="confirmEmail" type="email" autoComplete="off" required/></Label>{error&&<div className="error-box">{error}</div>}<div className="v2-dialog-actions"><Button type="button" variant="ghost" onClick={()=>setDeleteOpen(false)}>{t("cancel")}</Button><Button variant="destructive" disabled={deleting}>{deleting?t("deleting"):t("deleteForever")}</Button></div></form></DialogContent></Dialog><V2SuccessDialog open={success} onOpenChange={setSuccess} title={t("profileUpdated")} description={t("profileUpdatedDescription")}/></div>;
}
