"use client";
/* eslint-disable @next/next/no-img-element */
import { Camera, Leaf, Upload } from "lucide-react";
import { FormEvent, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiClient } from "@/lib/api-client";
import { session } from "@/lib/session";
import { getErrorMessage } from "@/lib/utils";
import type { User } from "@/types/contracts";
import { usePreferences } from "@/components/providers/preferences-provider";
export function V2ProfileOnboarding({user,onUpdated}:{user:User;onUpdated:(user:User)=>void}){const{t}=usePreferences();const[open,setOpen]=useState(!user.profileCompleted);const[avatar,setAvatar]=useState<File|null>(null);const[preview,setPreview]=useState(user.avatarUrl||"");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const fileRef=useRef<HTMLInputElement>(null);function select(file?:File){if(!file)return;setAvatar(file);setPreview(URL.createObjectURL(file));}async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const displayName=String(new FormData(event.currentTarget).get("displayName")||"").trim();if(!avatar&&!user.avatarUrl)return setError(t("chooseAvatarError"));setSaving(true);setError("");try{let updated=await apiClient<User>(`/users/${user.id}`,{method:"PATCH",body:JSON.stringify({displayName})});if(avatar){const body=new FormData();body.append("avatar",avatar);updated=await apiClient<User>(`/users/${user.id}/avatar`,{method:"POST",body});}session.updateUser(updated);onUpdated(updated);setOpen(false);}catch(reason){setError(getErrorMessage(reason));}finally{setSaving(false);}}return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="v2-onboarding"><div className="v2-onboarding-leaf"><Leaf/></div><DialogHeader><p className="v2-eyebrow">{t("quickSetup")}</p><DialogTitle>{t("callYouRight")}</DialogTitle><DialogDescription>{t("onboardingDescription")}</DialogDescription></DialogHeader><form onSubmit={submit}><button className="v2-avatar-uploader" type="button" onClick={()=>fileRef.current?.click()}><span>{preview?<img src={preview} alt={t("selectedAvatar")}/>:<Camera/>}</span><span><strong>{avatar?avatar.name:t("chooseAvatar")}</strong><small>{t("avatarTypes")}</small></span><Upload/></button><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>select(event.target.files?.[0])}/><Label>{t("displayName")}<Input name="displayName" defaultValue={user.displayName||""} placeholder={t("namePlaceholder")} required maxLength={60}/></Label>{error&&<div className="error-box">{error}</div>}<div className="v2-dialog-actions"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>{t("later")}</Button><Button disabled={saving}>{saving?t("saving"):t("finishProfile")}</Button></div></form></DialogContent></Dialog>;}
